### ISSUE TITLE
handleAPGet returns status code 500 on File not found

### ISSUE THREAD

**Issue by oddstr13** [nrwiersma/ConfigManager#10]
The correct status code for `Not found` is `404`.

https://github.com/nrwiersma/ConfigManager/blob/master/src/ConfigManager.cpp#L50
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

**Comment by nrwiersma** [comment]
Hi, You are quiet right, not sure what i was thinking. Would you like to supply a pull request? If not I can fix it.

**Comment by nrwiersma** [comment]
Fixed in version 0.8
