### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by unimogman** [nrwiersma/ConfigManager#111]
When im compiling the Configmanager (in VS code with platform IO), I get the folowing warning:

![image](https://user-images.githubusercontent.com/15200222/131220499-fc77f748-1b77-412c-a66d-337b36d7beca.png)

I was able to fix it by adding "const", is it possible to also change this in the library?
![image](https://user-images.githubusercontent.com/15200222/131220479-c6cff0f0-3545-4836-9749-df6e6c0010d3.png)

**Comment by cgmckeever** [comment]
submit a pull request and it'll be reviewed .. thanks
