### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by Frtrillo** [nrwiersma/ConfigManager#115]
![image](https://user-images.githubusercontent.com/72965099/139963404-cf49af89-a77a-465e-8010-62feccf62a98.png)
How can we set the webserver to ignore cors policy?

**Comment by nrwiersma** [comment]
You would need to add `server.sendHeader("Access-Control-Allow-Origin", "*");` to all `handle*` functions in the lib. A pull request to this effect would be welcome.

**Comment by Frtrillo** [comment]
> You would need to add `server.sendHeader("Access-Control-Allow-Origin", "*");` to all `handle*` functions in the lib. A pull request to this effect would be welcome.

Im willing to do it but it still isn't working. I've added it like this:
![image](https://user-images.githubusercontent.com/72965099/140026907-4846349a-2a86-4299-9eaf-49105f357242.png)
And now im getting a different error:

![image](https://user-images.githubusercontent.com/72965099/140027054-dced2b08-98d9-4280-8df9-6e9726a1ce46.png)

**Comment by nrwiersma** [comment]
Chrome does not support CORS on localhost. That is the reason for the other issue.

**Comment by Frtrillo** [comment]
> Chrome does not support CORS on localhost. That is the reason for the other issue.
Angular app will do the request from localhost though, which is one of the mainly (and good) uses for the library I think. Somehow throught browser is working /scan:
![image](https://user-images.githubusercontent.com/72965099/140038265-31ef627c-5b5e-4ea4-86f9-08bfc95cd1a1.png)
And im getting the networks json. But it isn't working on the phone indeed.

What I still can't make it to work is to POST:
![image](https://user-images.githubusercontent.com/72965099/140031963-48092a25-141e-4acd-937c-af966151648c.png)

Maybe adding something like send status 200 would work?

**Comment by nrwiersma** [comment]
The issue is that your server is on localhost, and chrome has blocked CORS on localhost: https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work

**Comment by Frtrillo** [comment]
> The issue is that your server is on localhost, and chrome has blocked CORS on localhost: https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work

I've fixed it to work on the localhost browser too, Ill do a pull request later
