### ISSUE TITLE
How can I make it to auto reconnect?

### ISSUE THREAD

**Issue by Frtrillo** [nrwiersma/ConfigManager#117]
Im trying to make the library (or sketch) to auto reconnect wifi after it connected successfully. Because right now once its connected and if wifi stops working and works again, it won't reconnect and connexions wont work.

I've tried something like this modifiying the library but its not working:

```
 if ((WiFi.status() != WL_CONNECTED)) {
    delay(1000);
    yield();
    char ssid[SSID_LENGTH];
    char password[PASSWORD_LENGTH];
    EEPROM.get(MAGIC_LENGTH, ssid);
    EEPROM.get(MAGIC_LENGTH + SSID_LENGTH, password);
    Serial.print("Reconnecting");
    WiFi.begin(ssid, password);
  }
```

**Comment by nrwiersma** [comment]
You should try calling `WiFi.reconnect()`.

**Comment by Frtrillo** [comment]
> You should try calling `WiFi.reconnect()`.

Tried that first on the ::loop method and didn't worked

**Comment by cgmckeever** [comment]
you might need to call `ConfigManager::wifiConnected()` (or similiar) to first check status and the reconnect .. or it may perpetually do some reconnect on/off thing

**Comment by Frtrillo** [comment]
> > You should try calling `WiFi.reconnect()`.
> 
> Tried that first on the ::loop method and didn't worked

Using it inside the sketch instead have worked
