### ISSUE TITLE
Nice but the example doesn't work.

### ISSUE THREAD

**Issue by nardev** [nrwiersma/ConfigManager#12]
I just compiled/uploaded this to a ESP8266, it boots, makest AP, i connected but no way to get in.
Expected urls don't work..

**Comment by nrwiersma** [comment]
Hi,

Can you give more information please. It is difficult to know what is going on from your description.

Thanks

**Comment by nrwiersma** [comment]
Going to close this due to lack of activity, if you still having an issue, please re-open and I will gladly help where I can.

**Comment by menan** [comment]
I faced this issue. 

when I call `configManager.setAPICallback(createCustomRoute);` before `configManager.begin(config);` instead of after, it worked. Thanks the library @nardev.

**Comment by nrwiersma** [comment]
Thanks, you are correct, if it starts the API really fast, this might be the case. I will move it before in the example. Thanks for reporting.
