### ISSUE TITLE
Clear-text passwords exposed in GET api

### ISSUE THREAD

**Issue by JonSilver** [nrwiersma/ConfigManager#14]
The GET api passes the contents of all custom field to the client in clear text. Any custom fields which carry sensitive information, e.g. MQTT broker passwords, are therefore easy security breach targets.

I previously suggested:
1. implement an optional flag on custom fields which requests that some sort of two-way encryption/hashing be used to store and retrieve the custom field
2. the GET api doesn't bother decrypting these fields before sending to the client

However, I think it might be sufficient to still store password fields in clear text but send them obscured by filling the field's buffer with asterisks *.

How do you feel about that Nick?

Continued from previous discussion in issue #11

**Comment by nrwiersma** [comment]
Hi,

I like the suggestion of the asterisks. Another idea is to add a new function ```addSetParameter``` that does not return the parameter in the GET at all. How does that sound?

Thanks,
Nick

**Comment by JonSilver** [comment]
That sounds like a very good idea, Nick.

**Comment by nrwiersma** [comment]
Got this done, let me know what you think.
