### ISSUE TITLE
Compile error - simple.ino

### ISSUE THREAD

**Issue by RudyFiero** [nrwiersma/ConfigManager#2]
I get the following compile error

C:\Users\Rudy\Documents\Arduino\libraries\ConfigManager-master\examples\simple\simple.ino: In function 'void setup()':

simple:10: error: 'configManager' was not declared in this scope

     configManager.setAPName("Demo");

     ^

C:\Users\Rudy\Documents\Arduino\libraries\ConfigManager-master\examples\simple\simple.ino: In function 'void loop()':

simple:20: error: 'configManager' was not declared in this scope

     configManager.loop();

     ^

**Comment by nrwiersma** [comment]
Hi, I am aware of the issue. It will be fixed in the next release. Add
"configManager ConfigManager" above the setup function.

Thanks.

**Comment by nrwiersma** [comment]
Hi,

I have just uploaded some changes, they will only appear in the Arduino Library in around 24 hours. I have fixed the example as well as made some changes to the ```data/index.html```. This should fix your issue.

I will close this issue for now, let me know if you have any other issues.
