### ISSUE TITLE
'class ConfigManager' has no member named 'reset'

### ISSUE THREAD

**Issue by dsokac** [nrwiersma/ConfigManager#25]
`configManager.reset();`
The version I am using is: 1.2.0

**Comment by nrwiersma** [comment]
I am confused by the question. ConfigManager does not has a reset function. Where did you find the example code that includes it?

**Comment by dsokac** [comment]
https://ubidots.com/blog/connect-your-esp8266-to-any-available-wi-fi-network/

I used their code... is this anyway needed?

**Comment by dsokac** [comment]
Thank you for quick responses :) wish you all the best, and let me know if you find out something I may want to know.

**Comment by nrwiersma** [comment]
Hi,

Just to let you know, it seems the article points to a fork of my code (a friend pointed this out, I completely missed it). It can be found here:
https://github.com/mariacarlinahernandez/ConfigManager/tree/maka/ConfigManagerForked

Thanks,
Nick
