### ISSUE TITLE
Secure the AP with PASSWORD

### ISSUE THREAD

**Issue by bigoper** [nrwiersma/ConfigManager#31]
Thank you for an amazing Library!

Scenario:
- The device is now in AP mode.

Issue:
- The AP is not secured

Request:
- Is it possible to secure the AP with a PASSWORD?

Thanks!

**Comment by nrwiersma** [comment]
No worries. This goes against most use cases, but it should be fairly straight forward to support. If I make a branch for this, would you be able to test it for me?

**Comment by bigoper** [comment]
Sure, with pleasure.
Just let me know when.

Many thanks!

**Comment by bigoper** [comment]
Sure, I'll do it today.
I'll post the results ASAP.

Thanks!

**Comment by aviivgi** [comment]
I've tested the new branch -> works like a charm!
Thank you so much for the quick response/update.

Keep doing what you're doing :)

**Comment by bigoper** [comment]
I've tested the new branch -> works like a charm!
Thank you so much for the quick response/update.

Keep doing what you're doing :)

**Comment by nrwiersma** [comment]
Awesome, glad it works. I will then merge this into master and tag a new version. After that the branch will be deleted.
