### ISSUE TITLE
Add ConfigManager ArduBadge (Installation Guide)

### ISSUE THREAD

**Issue by gilmaimon** [nrwiersma/ConfigManager#39]
Hi!

A nice addition to the readme page can be an ArduBadge badge, see here: www.ardu-badge.com
For ConfigManager it will look like that:
[![arduino-library-badge](http://www.ardu-badge.com/badge/ConfigManager.svg)](http://www.ardu-badge.com/ConfigManager)
Markdown:
`[![arduino-library-badge](http://www.ardu-badge.com/badge/ConfigManager.svg)](http://www.ardu-badge.com/ConfigManager)`

It shows:
1. That ConfigManager is in the "Library Manager" in the Arduino IDE
2. The latest release version
3. Clicking on it redirects to a custom page with explanation on how to install ConfigManager.

What do you think?

**Comment by nrwiersma** [comment]
Nice idea. I will add it, thanks.
