### ISSUE TITLE
ArduinoJson 6 incompatibility

### ISSUE THREAD

**Issue by JonSilver** [nrwiersma/ConfigManager#42]
The library should either be updated to be compatible with breaking changes in ArduinoJson 6, or the documentation augmented to advise that ArduinoJson 5 be used.
In the meantime, for anyone reading this who uses PlatformIO, you can specify explicit use of the last version of ArduinoJson 5 by adding the following to `platformio.ini`:

    lib_deps =
        ArduinoJson@5.13.4

**Comment by nrwiersma** [comment]
Thanks. I have done as you suggested and stated in the library.json and the readme that version 5 is used. Version 6 has a fair number of changes.

**Comment by rishabhrkaushik** [comment]
Any plans for migrating to ArduinoJSON 6 in near future?

**Comment by nrwiersma** [comment]
Not right now. Did look at it briefly, but it is a large break between the versions, so will have to figure out how to use it again.

**Comment by JonSilver** [comment]
In the meantime @nrwiersma if I happen to get there first then I'll let you know and submit a PR.

**Comment by nrwiersma** [comment]
Thanks, always appreciate the help.

**Comment by ReneHezser** [comment]
Just wanted to check if there is any progress in the port to V6.

**Comment by nrwiersma** [comment]
@ReneHezser It is not a focus of mine at the moment. If you would like to contribute the conversion that would be great.

**Comment by ReneHezser** [comment]
I did :-)
My tests with ESP8266 and ESP32 with both examples succeeded.
