### ISSUE TITLE
add other text field to settings.html and read data ??? 

### ISSUE THREAD

**Issue by trangservice** [nrwiersma/ConfigManager#44]
I want to add text fields in settings.html And read the data, type out via Serial.println (variable) after saving in the form, such as mqtt_host from the example, want to read the data to be stored at the variable
Help explain me
Thank You

**Comment by nrwiersma** [comment]
Hi,

You should look at the [save config demo](https://github.com/nrwiersma/ConfigManager/tree/master/examples/save_config_demo). This does what you are looking for.

**Comment by trangservice** [comment]
Thank @nrwiersma
I got it.... from your example...
