### ISSUE TITLE
Cannot save config bool on v1.5.1

### ISSUE THREAD

**Issue by te260701** [nrwiersma/ConfigManager#69]
Hi there,

Merry Christmas :)
I just upgrade to v1.5.1 and try to add bool parameter and int parameter to config but it bool param won't save, int param OK.

EDIT: I found issue with main.js which is not create json data properly.
Here the code I edit. (I'm not expert in anyway so, wait for developer to come up with better solution lol)

```
  $.fn.serializeObject = function() {
    var o = {};
    var a = this.serializeArray();
    $.each(a, function() {
      var input = document.getElementsByName(this.name);
      var value = this.value;
      var dataType = input[0].getAttribute("data-type");
      if (dataType == "number") value = parseFloat(value);
      //The following line was added
      if (dataType == "bool") {
		  value = (value=="true" || value==1)? true:false;
      }  
      //End
      if (o[this.name]) {
        if (!o[this.name].push) {
          o[this.name] = [o[this.name]];
        }
        o[this.name].push(value || '');
      } else {
        o[this.name] = (value==null) ? '' : value; // This line was changed
      }
    });
    return o;
  };

```

**Comment by IceBearZero** [comment]
Yeah, this is one of the reasons that `data-type` attribute was in there. There is probably a more elegant way to do this in JS, but this works ;)

**Comment by te260701** [comment]
@nrwiersma 
It does correctly save data but it does not have JS to set value (checked) for boolean checkbox.

**Comment by nrwiersma** [comment]
@te260701  This is now fixed.
