### ISSUE TITLE
Example sketch for fsbrowser.ino

### ISSUE THREAD

**Issue by te260701** [nrwiersma/ConfigManager#73]
Hi,

Could you please provide example like fsbrowser.ino https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/FSBrowser/FSBrowser.ino

I try to upload/update html file on spiffs using web browser.
I have custom route for upload
```
 server->on("/upload", HTTPMethod::HTTP_POST, [server](){
        server->send(200);
        handleFileUpload(server);
    });
```

```
void handleFileUpload(WebServer *server){ // upload a new file to the SPIFFS
  HTTPUpload& upload = server->upload();
  if(upload.status == UPLOAD_FILE_START){
    String filename = upload.filename;
    if(!filename.startsWith("/")) filename = "/"+filename;
    Serial.print("handleFileUpload Name: "); Serial.println(filename);
    fsUploadFile = SPIFFS.open(filename, "w");            // Open the file for writing in SPIFFS (create if it doesn't exist)
    filename = String();
  } else if(upload.status == UPLOAD_FILE_WRITE){
    if(fsUploadFile)
      fsUploadFile.write(upload.buf, upload.currentSize); // Write the received bytes to the file
  } else if(upload.status == UPLOAD_FILE_END){
    if(fsUploadFile) {                                    // If the file was successfully created
      fsUploadFile.close();                               // Close the file again
      Serial.print("handleFileUpload Size: "); Serial.println(upload.totalSize);
      server->sendHeader("Location","/success.html");      // Redirect the client to the success page
      server->send(303);
    } else {
      server->send(500, "text/plain", "500: couldn't create file");
    }
  }
}
```
I copied handleFileUpload for example and pass `server` to the function and change `server.xxx` to `server->xxx`. It did compiled just fine but it doesn't response at all, just blank page after `server->send(200)`.

I think I have no idea how to refer to `server` instance.

Thank you,
sam

**Comment by nrwiersma** [comment]
Hi,

You can get access to the server object through the [API callback](https://github.com/nrwiersma/ConfigManager#setapicallback). 

Past that you will need to seek help in the ESP8266 Arduino forums. This is not the right place to find general help on ESP8266 development.
