### ISSUE TITLE
Timeout does not work

### ISSUE THREAD

**Issue by diego1971** [nrwiersma/ConfigManager#74]
Hi, I tried to set the timeout to 300 on configmanager.h, but esp8266 doesn't reboot.

**Comment by nrwiersma** [comment]
Can you give some more info? You waited 5 minutes in AP mode and it never rebooted? Can you show code?

**Comment by diego1971** [comment]
Thanks a lot Nicolas, I was wrong to insert the timeout. sorry if I
bothered you.

Diego

Il giorno mar 14 gen 2020 alle ore 18:09 Nicholas Wiersma <
notifications@github.com> ha scritto:
