### ISSUE TITLE
image file (.jpg/.png) cannot be used in index.html

### ISSUE THREAD

**Issue by thanawat14** [nrwiersma/ConfigManager#84]
I try to use an image in html file but the image doesn't show up when I connect the a default webpage.

img src="image.png" alt="logo" style="width:25%;"

PS: I have image.png in data folder.

**Comment by nrwiersma** [comment]
ConfigManager does not allow serving arb files from the SPIFFS. This would be a feature in its own right.

**Comment by cgmckeever** [comment]
Could you add a [mime/file such as ](https://github.com/nrwiersma/ConfigManager/blob/master/examples/save_config_demo/save_config_demo.ino#L4)
```
const char *imagePNG = (char *)"/image.png";
```

and then 

```
server->on("/image.png", HTTPMethod::HTTP_GET, [server](){
        configManager.streamFile(imagePNG, mimePNG);
    });
```

you'd hav to define the `mimePNG` I believe at this point as well ...

**Comment by thanawat14** [comment]
Sorry for my late reply. I decided to use base64 instead, and the problem was solved. Thank you.
