### ISSUE TITLE
ESP32 Wifi Sucks .. connects every two tries .. Workaround thoughts 

### ISSUE THREAD

**Issue by cgmckeever** [nrwiersma/ConfigManager#95]
[Related Issue](https://github.com/espressif/arduino-esp32/issues/2501)

Appears the ESP32 really sucks ... Currently running into a Wifi connection only happens every other boot.
Workaround appears to be something like this .. but its gross ...  

Thoughts? Can add some `flag` to enable this so it doesnt always double tap? 

```

WiFi.begin(ssid, password[0] == '\0' ? NULL : password);
delay(1000);
WiFi.disconnect();
WiFi.begin(ssid, password[0] == '\0' ? NULL : password);

```

```
Reading saved configuration
SSID: "BI-12"
E (1003) wifi: Set status to INIT.
 
========= ABOVE DELAY/CONNECT CODE ==========

Waiting for WiFi to connect...
Connected to BI-12 with 192.168.4.3
Station Mode

```

**Comment by nrwiersma** [comment]
I find it surprising how long such a critical bug has been around.

As you point out, that is not a good workaround. Not gonna lie, would not be happy with that in the codebase.

However, should the `disconnect` not be needed, I would not be opposed to a retry loop with a fixed number of retries. Something like:
```
for (var i = 0; i < 3; i++) {
  WiFi.begin(ssid, password[0] == '\0' ? NULL : password);

   if (wifiConnected()) {
     break;
   }
  delay(1000);
}
```

**Comment by cgmckeever** [comment]
> Not gonna lie, would not be happy with that in the codebase.

Hence why I didnt even attempt a PRr yet ... I like the retry loop -- will work on it later

**Comment by cgmckeever** [comment]
https://github.com/nrwiersma/ConfigManager/pull/96
